### YamlMime:ManagedReference
items:
- uid: Models.Settings.Theme.CTheme
  commentId: T:Models.Settings.Theme.CTheme
  id: CTheme
  parent: Models.Settings.Theme
  children:
  - Models.Settings.Theme.CTheme.#ctor
  - Models.Settings.Theme.CTheme.CurrentLayout
  - Models.Settings.Theme.CTheme.CurrentTheme
  - Models.Settings.Theme.CTheme.LayoutsTheme
  langs:
  - csharp
  - vb
  name: CTheme
  nameWithType: CTheme
  fullName: Models.Settings.Theme.CTheme
  type: Class
  source:
    remote:
      path: EasySave-2.0/EasySaveGUI/Models/Settings/Theme/CTheme.cs
      branch: develop-livrable-2
      repo: https://faikmehmeti@dev.azure.com/faikmehmeti/G4-FISA-24/_git/G4-FISA-24
    id: CTheme
    path: ../G4-FISA-24/EasySave-2.0/EasySaveGUI/Models/Settings/Theme/CTheme.cs
    startLine: 7
  assemblies:
  - Models
  namespace: Models.Settings.Theme
  summary: Classe model du theme utilisateur
  example: []
  syntax:
    content: >-
      [DataContract]

      public class CTheme
    content.vb: >-
      <DataContract>

      Public Class CTheme
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  attributes:
  - type: System.Runtime.Serialization.DataContractAttribute
    ctor: System.Runtime.Serialization.DataContractAttribute.#ctor
    arguments: []
- uid: Models.Settings.Theme.CTheme.LayoutsTheme
  commentId: P:Models.Settings.Theme.CTheme.LayoutsTheme
  id: LayoutsTheme
  parent: Models.Settings.Theme.CTheme
  langs:
  - csharp
  - vb
  name: LayoutsTheme
  nameWithType: CTheme.LayoutsTheme
  fullName: Models.Settings.Theme.CTheme.LayoutsTheme
  type: Property
  source:
    remote:
      path: EasySave-2.0/EasySaveGUI/Models/Settings/Theme/CTheme.cs
      branch: develop-livrable-2
      repo: https://faikmehmeti@dev.azure.com/faikmehmeti/G4-FISA-24/_git/G4-FISA-24
    id: LayoutsTheme
    path: ../G4-FISA-24/EasySave-2.0/EasySaveGUI/Models/Settings/Theme/CTheme.cs
    startLine: 19
  assemblies:
  - Models
  namespace: Models.Settings.Theme
  summary: Les theme lié aux layouts
  example: []
  syntax:
    content: public Dictionary<string, ETheme> LayoutsTheme { get; set; }
    parameters: []
    return:
      type: System.Collections.Generic.Dictionary{System.String,Models.Settings.Theme.ETheme}
    content.vb: Public Property LayoutsTheme As Dictionary(Of String, ETheme)
  overload: Models.Settings.Theme.CTheme.LayoutsTheme*
- uid: Models.Settings.Theme.CTheme.CurrentLayout
  commentId: P:Models.Settings.Theme.CTheme.CurrentLayout
  id: CurrentLayout
  parent: Models.Settings.Theme.CTheme
  langs:
  - csharp
  - vb
  name: CurrentLayout
  nameWithType: CTheme.CurrentLayout
  fullName: Models.Settings.Theme.CTheme.CurrentLayout
  type: Property
  source:
    remote:
      path: EasySave-2.0/EasySaveGUI/Models/Settings/Theme/CTheme.cs
      branch: develop-livrable-2
      repo: https://faikmehmeti@dev.azure.com/faikmehmeti/G4-FISA-24/_git/G4-FISA-24
    id: CurrentLayout
    path: ../G4-FISA-24/EasySave-2.0/EasySaveGUI/Models/Settings/Theme/CTheme.cs
    startLine: 23
  assemblies:
  - Models
  namespace: Models.Settings.Theme
  summary: Layout actuel
  example: []
  syntax:
    content: public string CurrentLayout { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property CurrentLayout As String
  overload: Models.Settings.Theme.CTheme.CurrentLayout*
- uid: Models.Settings.Theme.CTheme.CurrentTheme
  commentId: P:Models.Settings.Theme.CTheme.CurrentTheme
  id: CurrentTheme
  parent: Models.Settings.Theme.CTheme
  langs:
  - csharp
  - vb
  name: CurrentTheme
  nameWithType: CTheme.CurrentTheme
  fullName: Models.Settings.Theme.CTheme.CurrentTheme
  type: Property
  source:
    remote:
      path: EasySave-2.0/EasySaveGUI/Models/Settings/Theme/CTheme.cs
      branch: develop-livrable-2
      repo: https://faikmehmeti@dev.azure.com/faikmehmeti/G4-FISA-24/_git/G4-FISA-24
    id: CurrentTheme
    path: ../G4-FISA-24/EasySave-2.0/EasySaveGUI/Models/Settings/Theme/CTheme.cs
    startLine: 27
  assemblies:
  - Models
  namespace: Models.Settings.Theme
  summary: Theme actuel
  example: []
  syntax:
    content: public ETheme CurrentTheme { get; set; }
    parameters: []
    return:
      type: Models.Settings.Theme.ETheme
    content.vb: Public Property CurrentTheme As ETheme
  overload: Models.Settings.Theme.CTheme.CurrentTheme*
- uid: Models.Settings.Theme.CTheme.#ctor
  commentId: M:Models.Settings.Theme.CTheme.#ctor
  id: '#ctor'
  parent: Models.Settings.Theme.CTheme
  langs:
  - csharp
  - vb
  name: CTheme()
  nameWithType: CTheme.CTheme()
  fullName: Models.Settings.Theme.CTheme.CTheme()
  type: Constructor
  source:
    remote:
      path: EasySave-2.0/EasySaveGUI/Models/Settings/Theme/CTheme.cs
      branch: develop-livrable-2
      repo: https://faikmehmeti@dev.azure.com/faikmehmeti/G4-FISA-24/_git/G4-FISA-24
    id: .ctor
    path: ../G4-FISA-24/EasySave-2.0/EasySaveGUI/Models/Settings/Theme/CTheme.cs
    startLine: 39
  assemblies:
  - Models
  namespace: Models.Settings.Theme
  summary: Contructeur du theme initialise le dictionnaire de layout
  example: []
  syntax:
    content: public CTheme()
    content.vb: Public Sub New()
  overload: Models.Settings.Theme.CTheme.#ctor*
  nameWithType.vb: CTheme.New()
  fullName.vb: Models.Settings.Theme.CTheme.New()
  name.vb: New()
references:
- uid: Models.Settings.Theme
  commentId: N:Models.Settings.Theme
  href: Models.html
  name: Models.Settings.Theme
  nameWithType: Models.Settings.Theme
  fullName: Models.Settings.Theme
  spec.csharp:
  - uid: Models
    name: Models
    href: Models.html
  - name: .
  - uid: Models.Settings
    name: Settings
    href: Models.Settings.html
  - name: .
  - uid: Models.Settings.Theme
    name: Theme
    href: Models.Settings.Theme.html
  spec.vb:
  - uid: Models
    name: Models
    href: Models.html
  - name: .
  - uid: Models.Settings
    name: Settings
    href: Models.Settings.html
  - name: .
  - uid: Models.Settings.Theme
    name: Theme
    href: Models.Settings.Theme.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Models.Settings.Theme.CTheme.LayoutsTheme*
  commentId: Overload:Models.Settings.Theme.CTheme.LayoutsTheme
  href: Models.Settings.Theme.CTheme.html#Models_Settings_Theme_CTheme_LayoutsTheme
  name: LayoutsTheme
  nameWithType: CTheme.LayoutsTheme
  fullName: Models.Settings.Theme.CTheme.LayoutsTheme
- uid: System.Collections.Generic.Dictionary{System.String,Models.Settings.Theme.ETheme}
  commentId: T:System.Collections.Generic.Dictionary{System.String,Models.Settings.Theme.ETheme}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.Dictionary`2
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.dictionary-2
  name: Dictionary<string, ETheme>
  nameWithType: Dictionary<string, ETheme>
  fullName: System.Collections.Generic.Dictionary<string, Models.Settings.Theme.ETheme>
  nameWithType.vb: Dictionary(Of String, ETheme)
  fullName.vb: System.Collections.Generic.Dictionary(Of String, Models.Settings.Theme.ETheme)
  name.vb: Dictionary(Of String, ETheme)
  spec.csharp:
  - uid: System.Collections.Generic.Dictionary`2
    name: Dictionary
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.dictionary-2
  - name: <
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: ','
  - name: " "
  - uid: Models.Settings.Theme.ETheme
    name: ETheme
    href: Models.Settings.Theme.ETheme.html
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.Dictionary`2
    name: Dictionary
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.dictionary-2
  - name: (
  - name: Of
  - name: " "
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: ','
  - name: " "
  - uid: Models.Settings.Theme.ETheme
    name: ETheme
    href: Models.Settings.Theme.ETheme.html
  - name: )
- uid: System.Collections.Generic.Dictionary`2
  commentId: T:System.Collections.Generic.Dictionary`2
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.dictionary-2
  name: Dictionary<TKey, TValue>
  nameWithType: Dictionary<TKey, TValue>
  fullName: System.Collections.Generic.Dictionary<TKey, TValue>
  nameWithType.vb: Dictionary(Of TKey, TValue)
  fullName.vb: System.Collections.Generic.Dictionary(Of TKey, TValue)
  name.vb: Dictionary(Of TKey, TValue)
  spec.csharp:
  - uid: System.Collections.Generic.Dictionary`2
    name: Dictionary
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.dictionary-2
  - name: <
  - name: TKey
  - name: ','
  - name: " "
  - name: TValue
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.Dictionary`2
    name: Dictionary
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.dictionary-2
  - name: (
  - name: Of
  - name: " "
  - name: TKey
  - name: ','
  - name: " "
  - name: TValue
  - name: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
- uid: Models.Settings.Theme.CTheme.CurrentLayout*
  commentId: Overload:Models.Settings.Theme.CTheme.CurrentLayout
  href: Models.Settings.Theme.CTheme.html#Models_Settings_Theme_CTheme_CurrentLayout
  name: CurrentLayout
  nameWithType: CTheme.CurrentLayout
  fullName: Models.Settings.Theme.CTheme.CurrentLayout
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Models.Settings.Theme.CTheme.CurrentTheme*
  commentId: Overload:Models.Settings.Theme.CTheme.CurrentTheme
  href: Models.Settings.Theme.CTheme.html#Models_Settings_Theme_CTheme_CurrentTheme
  name: CurrentTheme
  nameWithType: CTheme.CurrentTheme
  fullName: Models.Settings.Theme.CTheme.CurrentTheme
- uid: Models.Settings.Theme.ETheme
  commentId: T:Models.Settings.Theme.ETheme
  parent: Models.Settings.Theme
  href: Models.Settings.Theme.ETheme.html
  name: ETheme
  nameWithType: ETheme
  fullName: Models.Settings.Theme.ETheme
- uid: Models.Settings.Theme.CTheme.#ctor*
  commentId: Overload:Models.Settings.Theme.CTheme.#ctor
  href: Models.Settings.Theme.CTheme.html#Models_Settings_Theme_CTheme__ctor
  name: CTheme
  nameWithType: CTheme.CTheme
  fullName: Models.Settings.Theme.CTheme.CTheme
  nameWithType.vb: CTheme.New
  fullName.vb: Models.Settings.Theme.CTheme.New
  name.vb: New
