### YamlMime:ManagedReference
items:
- uid: Models.Settings
  commentId: T:Models.Settings
  id: Settings
  parent: Models
  children:
  - Models.Settings.Finalize
  - Models.Settings.Instance
  - Models.Settings.JobConfigPath
  - Models.Settings.Langue
  - Models.Settings.LoadSettings
  - Models.Settings.SaveSettings
  langs:
  - csharp
  - vb
  name: Settings
  nameWithType: Settings
  fullName: Models.Settings
  type: Class
  source:
    remote:
      path: EasySave-G4-FISA-24/Models/Settings.cs
      branch: develop-livrable-1
      repo: https://faikmehmeti@dev.azure.com/faikmehmeti/G4-FISA-24/_git/G4-FISA-24
    id: Settings
    path: ../G4-FISA-24/EasySave-G4-FISA-24/Models/Settings.cs
    startLine: 5
  assemblies:
  - Models
  namespace: Models
  syntax:
    content: >-
      [DataContract]

      public class Settings
    content.vb: >-
      <DataContract>

      Public Class Settings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  attributes:
  - type: System.Runtime.Serialization.DataContractAttribute
    ctor: System.Runtime.Serialization.DataContractAttribute.#ctor
    arguments: []
- uid: Models.Settings.Langue
  commentId: P:Models.Settings.Langue
  id: Langue
  parent: Models.Settings
  langs:
  - csharp
  - vb
  name: Langue
  nameWithType: Settings.Langue
  fullName: Models.Settings.Langue
  type: Property
  source:
    remote:
      path: EasySave-G4-FISA-24/Models/Settings.cs
      branch: develop-livrable-1
      repo: https://faikmehmeti@dev.azure.com/faikmehmeti/G4-FISA-24/_git/G4-FISA-24
    id: Langue
    path: ../G4-FISA-24/EasySave-G4-FISA-24/Models/Settings.cs
    startLine: 18
  assemblies:
  - Models
  namespace: Models
  syntax:
    content: public CLangue Langue { get; set; }
    parameters: []
    return:
      type: Models.CLangue
    content.vb: Public Property Langue As CLangue
  overload: Models.Settings.Langue*
- uid: Models.Settings.JobConfigPath
  commentId: P:Models.Settings.JobConfigPath
  id: JobConfigPath
  parent: Models.Settings
  langs:
  - csharp
  - vb
  name: JobConfigPath
  nameWithType: Settings.JobConfigPath
  fullName: Models.Settings.JobConfigPath
  type: Property
  source:
    remote:
      path: EasySave-G4-FISA-24/Models/Settings.cs
      branch: develop-livrable-1
      repo: https://faikmehmeti@dev.azure.com/faikmehmeti/G4-FISA-24/_git/G4-FISA-24
    id: JobConfigPath
    path: ../G4-FISA-24/EasySave-G4-FISA-24/Models/Settings.cs
    startLine: 19
  assemblies:
  - Models
  namespace: Models
  syntax:
    content: public string JobConfigPath { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property JobConfigPath As String
  overload: Models.Settings.JobConfigPath*
- uid: Models.Settings.Instance
  commentId: P:Models.Settings.Instance
  id: Instance
  parent: Models.Settings
  langs:
  - csharp
  - vb
  name: Instance
  nameWithType: Settings.Instance
  fullName: Models.Settings.Instance
  type: Property
  source:
    remote:
      path: EasySave-G4-FISA-24/Models/Settings.cs
      branch: develop-livrable-1
      repo: https://faikmehmeti@dev.azure.com/faikmehmeti/G4-FISA-24/_git/G4-FISA-24
    id: Instance
    path: ../G4-FISA-24/EasySave-G4-FISA-24/Models/Settings.cs
    startLine: 22
  assemblies:
  - Models
  namespace: Models
  syntax:
    content: public static Settings Instance { get; }
    parameters: []
    return:
      type: Models.Settings
    content.vb: Public Shared ReadOnly Property Instance As Settings
  overload: Models.Settings.Instance*
- uid: Models.Settings.Finalize
  commentId: M:Models.Settings.Finalize
  id: Finalize
  parent: Models.Settings
  langs:
  - csharp
  - vb
  name: ~Settings()
  nameWithType: Settings.~Settings()
  fullName: Models.Settings.~Settings()
  type: Method
  source:
    remote:
      path: EasySave-G4-FISA-24/Models/Settings.cs
      branch: develop-livrable-1
      repo: https://faikmehmeti@dev.azure.com/faikmehmeti/G4-FISA-24/_git/G4-FISA-24
    id: Finalize
    path: ../G4-FISA-24/EasySave-G4-FISA-24/Models/Settings.cs
    startLine: 37
  assemblies:
  - Models
  namespace: Models
  syntax:
    content: protected ~Settings()
    content.vb: 'Protected '
  overload: Models.Settings.Finalize*
  nameWithType.vb: ''
  fullName.vb: ''
  name.vb: ''
- uid: Models.Settings.SaveSettings
  commentId: M:Models.Settings.SaveSettings
  id: SaveSettings
  parent: Models.Settings
  langs:
  - csharp
  - vb
  name: SaveSettings()
  nameWithType: Settings.SaveSettings()
  fullName: Models.Settings.SaveSettings()
  type: Method
  source:
    remote:
      path: EasySave-G4-FISA-24/Models/Settings.cs
      branch: develop-livrable-1
      repo: https://faikmehmeti@dev.azure.com/faikmehmeti/G4-FISA-24/_git/G4-FISA-24
    id: SaveSettings
    path: ../G4-FISA-24/EasySave-G4-FISA-24/Models/Settings.cs
    startLine: 49
  assemblies:
  - Models
  namespace: Models
  summary: Save Settings in a json file
  example: []
  syntax:
    content: public void SaveSettings()
    content.vb: Public Sub SaveSettings()
  overload: Models.Settings.SaveSettings*
- uid: Models.Settings.LoadSettings
  commentId: M:Models.Settings.LoadSettings
  id: LoadSettings
  parent: Models.Settings
  langs:
  - csharp
  - vb
  name: LoadSettings()
  nameWithType: Settings.LoadSettings()
  fullName: Models.Settings.LoadSettings()
  type: Method
  source:
    remote:
      path: EasySave-G4-FISA-24/Models/Settings.cs
      branch: develop-livrable-1
      repo: https://faikmehmeti@dev.azure.com/faikmehmeti/G4-FISA-24/_git/G4-FISA-24
    id: LoadSettings
    path: ../G4-FISA-24/EasySave-G4-FISA-24/Models/Settings.cs
    startLine: 58
  assemblies:
  - Models
  namespace: Models
  summary: Load Settigns from json file
  example: []
  syntax:
    content: public void LoadSettings()
    content.vb: Public Sub LoadSettings()
  overload: Models.Settings.LoadSettings*
references:
- uid: Models
  commentId: N:Models
  href: Models.html
  name: Models
  nameWithType: Models
  fullName: Models
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Models.Settings.Langue*
  commentId: Overload:Models.Settings.Langue
  href: Models.Settings.html#Models_Settings_Langue
  name: Langue
  nameWithType: Settings.Langue
  fullName: Models.Settings.Langue
- uid: Models.CLangue
  commentId: T:Models.CLangue
  parent: Models
  href: Models.CLangue.html
  name: CLangue
  nameWithType: CLangue
  fullName: Models.CLangue
- uid: Models.Settings.JobConfigPath*
  commentId: Overload:Models.Settings.JobConfigPath
  href: Models.Settings.html#Models_Settings_JobConfigPath
  name: JobConfigPath
  nameWithType: Settings.JobConfigPath
  fullName: Models.Settings.JobConfigPath
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Models.Settings.Instance*
  commentId: Overload:Models.Settings.Instance
  href: Models.Settings.html#Models_Settings_Instance
  name: Instance
  nameWithType: Settings.Instance
  fullName: Models.Settings.Instance
- uid: Models.Settings
  commentId: T:Models.Settings
  parent: Models
  href: Models.Settings.html
  name: Settings
  nameWithType: Settings
  fullName: Models.Settings
- uid: Models.Settings.Finalize*
  commentId: Overload:Models.Settings.Finalize
  href: Models.Settings.html#Models_Settings_Finalize
  name: ~Settings
  nameWithType: Settings.~Settings
  fullName: Models.Settings.~Settings
  spec.csharp:
  - name: "~"
  - uid: Models.Settings.Finalize*
    name: Settings
    href: Models.Settings.html#Models_Settings_Finalize
- uid: Models.Settings.SaveSettings*
  commentId: Overload:Models.Settings.SaveSettings
  href: Models.Settings.html#Models_Settings_SaveSettings
  name: SaveSettings
  nameWithType: Settings.SaveSettings
  fullName: Models.Settings.SaveSettings
- uid: Models.Settings.LoadSettings*
  commentId: Overload:Models.Settings.LoadSettings
  href: Models.Settings.html#Models_Settings_LoadSettings
  name: LoadSettings
  nameWithType: Settings.LoadSettings
  fullName: Models.Settings.LoadSettings
